export const SET_STEP = 'SET_STEP'
export const SET_USER = 'SET_USER'
export const EMAILADDRESS_REQUEST = 'EMAILADDRESS_REQUEST'
export const DEADLINE_REQUEST = 'DEADLINE_REQUEST'
export const SUBJECT_REQUEST = 'SUBJECT_REQUEST'
export const NUMPAGES_REQUEST = 'NUMPAGES_REQUEST'

export const TITLE_REQUEST = 'TITLE_REQUEST'
export const FORMAT_REQUEST = 'FORMAT_REQUEST'
export const LEVEL_REQUEST = 'LEVEL_REQUEST'
export const BUDGET_REQUEST = 'BUDGET_REQUEST'
export const ORDERDETAILS_REQUEST = 'ORDERDETAILS_REQUEST'
export const SETSPINNER_REQUEST = 'SETSPINNER_REQUEST'
export const SHOWLOGIN_REQUEST = 'SHOWLOGIN_REQUEST'
export const SHOWREGISTER_REQUEST = 'SHOWREGISTER_REQUEST'
export const CHECKAUTH_REQUEST = 'CHECKAUTH_REQUEST'

export const POSTHOMEWORK_REQUEST = 'POSTHOMEWORK_REQUEST'

export const REGITERUSERNAME_REQUEST = 'REGITERUSERNAME_REQUEST'
export const REGISTERFULLNAME_REQUEST = 'REGISTERFULLNAME_REQUEST'
export const REGISTERPASSWORD_REQUEST = 'REGISTERPASSWORD_REQUEST'
export const REGISTERCONFIRMPASSWORD_REQUEST = 'REGISTERCONFIRMPASSWORD_REQUEST'
export const POSTHOMEWORK_REGISTER_REQUEST = 'POSTHOMEWORK_REGISTER_REQUEST'
export const LOGINEMAILADDRESS_REQUEST = 'LOGINEMAILADDRESS_REQUEST'
export const LOGINPASSWORD_REQUEST = 'LOGINPASSWORD_REQUEST'
export const POSTHOMEWORK_LOGIN_REQUEST = 'POSTHOMEWORK_LOGIN_REQUEST'

export const LOGINSPINNER_REQUEST = 'LOGINSPINNER_REQUEST'
export const REGISTERSPINNER_REQUEST = 'REGISTERSPINNER_REQUEST'

export const AUTHERROR_REQUEST = 'AUTHERROR_REQUEST'

export const ESTIMATEPRICING = 'ESTIMATEPRICING'

export const SETESTIMATE_PRICE = 'SETESTIMATE_PRICE'
